### ISSUE TITLE
Release of Previous Versions (0.14, 0.15)

### ISSUE THREAD

**Issue by mmcky** [conda-forge/myst-nb-feedstock#19]
### Comment:

@bollwyvl is there a way I can setup PR's to release the two previous versions `0.14` and `0.15`?

**Comment by mmcky** [comment]
https://pypi.org/project/myst-nb/#history

**Comment by bollwyvl** [comment]
There is no automatic way to get the bot to do historic PRs at this time.

i did two manual PRs, #20 (to a temp branch) and #21 to `main`), and merged them both, and the bot will issue the next 0.16.x or 0.17 to `main`. let me know if you need anything else... otherwise imagine we can close this out.

**Comment by mmcky** [comment]
Ah OK. Absolute legend - thanks for the help @bollwyvl. Greatly appreciated
